# Generated by Django 3.2.4 on 2021-07-14 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Boleta',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField()),
                ('comentario', models.CharField(blank=True, max_length=100, null=True)),
                ('total', models.IntegerField()),
                ('id_user', models.IntegerField()),
                ('nombre_cliente', models.CharField(max_length=100)),
                ('nombre_servicio', models.CharField(max_length=30)),
                ('nombre_mecanico', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'boleta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField()),
                ('comentario', models.CharField(blank=True, max_length=200, null=True)),
                ('validado', models.BooleanField()),
            ],
            options={
                'db_table': 'servicio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tiposervicio',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100)),
                ('precio', models.IntegerField()),
            ],
            options={
                'db_table': 'tiposervicio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tipousuario',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'tipousuario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuarioescritorio',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre_usuario', models.CharField(max_length=100)),
                ('contrasena', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('primer_nombre', models.CharField(max_length=150)),
                ('segundo_nombre', models.CharField(blank=True, max_length=150, null=True)),
                ('apellido_paterno', models.CharField(max_length=150)),
                ('apellido_materno', models.CharField(max_length=150)),
                ('rut', models.IntegerField()),
                ('dv', models.CharField(max_length=1)),
                ('fecha_nacimiento', models.DateField()),
            ],
            options={
                'db_table': 'usuarioescritorio',
                'managed': False,
            },
        ),
    ]
