# Generated by Django 3.2.4 on 2021-07-25 14:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservadehora',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha_solicitud', models.DateTimeField()),
                ('asunto', models.CharField(max_length=200)),
                ('tiposervicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tiposervicio')),
                ('usuarioescritorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.usuarioescritorio')),
                ('usuarioweb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reserva', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reservadehora',
                'managed': True,
            },
        ),
    ]
